name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Compile with Maven
        run: mvn -B compile
      - name: Build package
        run: mvn -B package
      - name: List build outputs
        run: ls -la target/
      - name: Upload built JAR
        uses: actions/upload-artifact@v3
        with:
          name: JsonToolsApp
          path: target/JsonToolsApp.jar
      - name: Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
