name: Java CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile with Maven
        run: mvn -B compile

      - name: Build package
        run: mvn -B package

      - name: List build outputs
        run: ls -la target/

      - name: Upload built JAR
        uses: actions/upload-artifact@v4.6.2
        with:
          name: JsonToolsApp
          path: target/jsontoolsapp.jar

      - name: Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
